image: ruby:3.0.2

cache:
  key:
    files:
      - Gemfile.lock
    prefix: $CI_COMMIT_REF_SLUG
  paths:
    - vendor/ruby

stages:
  - build
  - test
  - security

setup:
  stage: build
  script:
    - curl -sL https://deb.nodesource.com/setup_18.x | bash -
    - apt-get update -qq
    - apt-get install -qq --no-install-recommends nodejs
    - apt-get upgrade -qq
    - apt-get clean
    - rm -rf /var/lib/apt/lists/*\
    - npm install -g yarn@1
    - bundle config set --local path 'vendor/ruby'
    - bin/setup

rspec:
  stage: test

  script:
    - apt-get update -qq
    - apt-get install -qq --no-install-recommends nodejs
    - apt-get upgrade -qq
    - apt-get clean
    - rm -rf /var/lib/apt/lists/*\
    - bundle config set --local path 'vendor/ruby'
    - bundle install
    - bundle exec rspec

audit:
  stage: security

  script:
    - apt-get update -qq
    - apt-get install -qq --no-install-recommends nodejs
    - apt-get upgrade -qq
    - apt-get clean
    - rm -rf /var/lib/apt/lists/*\
    - bundle config set --local path 'vendor/ruby'
    - bundle install
    - gem install bundler-audit