image: ruby:3.1.2

cache:
  key: 
    files:
      - Gemfile.lock
    prefix: $CI_COMMIT_REF_SLUG
  paths:
    - vendor/ruby

stages:
  - build
  - test
  - security

setup:
  stage: build
  script: 
    - apt-get update
    - bundle config set --local path 'vendor/ruby'
    - sudo bin/setup
    - gem install bundler-audit

rspec:
  stage: test

  script:
    - bundle install
    - bundle exec rspec

audit:
  stage: security

  script: 
    - bundle exec bundle-audit